let a=17;
let b=10;
console.log(a);
console.log(b);
console.log("Arithmetic Operations");
let sum=a+b;
console.log(sum);
let diff=a-b;
console.log(diff);
let mul=a*b;
console.log(mul);
let div=a/b;
console.log(div);
let pow=a**b;
console.log(pow);